version: 0.0
os: linux
files:
  - source: target/*
    destination: /opt/ec
#  - source: application*.properties
#    destination: /opt/ec
file_exists_behavior: OVERWRITE
permissions:
  - object: scripts/*
    pattern: "**"
    mode: 755
hooks:
  ApplicationStop:
    - location: scripts/ApplicationStop
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/BeforeInstall
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/AfterInstall
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/ApplicationStart
      timeout: 300
      runas: root
