version: 0.0
os: linux
files:
  - source: *.jar
    destination: /opt/ec
  - source: application*.properties
    destination: /opt/ec
hooks:
  BeforeInstall:
    - location: BeforeInstall
      timeout: 300
      runas: root
  AfterInstall:
    - location: AfterInstall
      timeout: 300
      runas: root
  ApplicationStart:
    - location: ApplicationStart
      timeout: 300
      runas: root