version: 0.0
os: linux
files:
  - source: target/*.jar
    destination: /opt/ec
  - source: application*.properties
    destination: /opt/ec
permissions:
  - object: scripts/*
    pattern: "**"
    mode: +x
hooks:
  BeforeInstall:
    - location: scripts/BeforeInstall
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/AfterInstall
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/ApplicationStart
      timeout: 300
      runas: root