#!/bin/bash -xe

echo "#### Start: After Install ####" >> /opt/ec/deploy.log

cd /opt/ec

ENV=`cat environment`
echo $ENV >> /opt/ec/deploy.log


echo "#### Done: After Install ####" >> /opt/ec/deploy.log
