#!/bin/bash -xe

pwd > /opt/ec/deploy.log
whoami >> /opt/ec/deploy.log
ls -ltr >> /opt/ec/deploy.log

rm -vf enrollment-challenge-*.jar >> /opt/ec/deploy.log
rm -vf application*.properties >> /opt/ec/deploy.log
